services:
  minio:
    image: quay.io/minio/minio
    container_name: minio-local
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000" 
      - "9090:9090" 
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address :9090

volumes:
  minio_data: {}
